name: taxbrain-dev
channels:
- conda-forge
dependencies:
- python>=3.6.5
- taxcalc>=3.1.0
- behresp>=0.11.0
- pandas>=0.23
- numpy>=1.14
- scipy
- paramtools>=0.18.1
- pytest
- dask
- distributed
- bokeh
- markdown
- tabulate
- pypandoc
- pip
- matplotlib
- s3fs
- pip:
  - cs-kit
  - cs2tc
